packages = [
    "pulseaudio",
    "pavucontrol",
    "firefox",
    "thunderbird",
    "screenfetch",
    "pamac-gtk",
    "pamac-snap-plugin",
    "pamac-flatpak-plugin",
    "mpv",
]

script = """
set -eux

systemctl enable apparmor
systemctl enable snapd.apparmor
systemctl enable snapd
"""
